// Données vérifiées manuellement (voir combattants-template.csv) — 20 combattants
// avec leurs vraies stats. Utilisé par le Simulateur, séparé des données live
// de l'API Octagon (qui n'a pas ces stats détaillées).
export const FIGHTERS = [
  { id: "f001", nom: "Islam Makhachev", categorie: "Poids welter", taille: 178, allonge: 178, victoires: 28, defaites: 1, nuls: 0, ko: 25, sub: 46, dec: 29, striking: 58, tdAcc: 56, tdDef: 91 },
  { id: "f002", nom: "Alex Pereira", categorie: "Poids lourd", taille: 193, allonge: 201, victoires: 13, defaites: 4, nuls: 0, ko: 85, sub: 0, dec: 15, striking: 61, tdAcc: 100, tdDef: 70 },
  { id: "f003", nom: "Justin Gaethje", categorie: "Poids leger", taille: 180, allonge: 178, victoires: 28, defaites: 5, nuls: 0, ko: 75, sub: 4, dec: 21, striking: 58, tdAcc: 26, tdDef: 74 },
  { id: "f004", nom: "Ilia Topuria", categorie: "Poids leger", taille: 170, allonge: 175, victoires: 17, defaites: 1, nuls: 0, ko: 41, sub: 47, dec: 12, striking: 46, tdAcc: 56, tdDef: 92 },
  { id: "f005", nom: "Alexander Volkanovski", categorie: "Poids plume", taille: 168, allonge: 182, victoires: 28, defaites: 4, nuls: 0, ko: 46, sub: 11, dec: 43, striking: 57, tdAcc: 37, tdDef: 70 },
  { id: "f006", nom: "Petr Yan", categorie: "Poids coq", taille: 171, allonge: 170, victoires: 20, defaites: 5, nuls: 0, ko: 35, sub: 5, dec: 60, striking: null, tdAcc: 19, tdDef: 82 },
  { id: "f007", nom: "Merab Dvalishvili", categorie: "Poids coq", taille: 168, allonge: 173, victoires: 21, defaites: 5, nuls: 0, ko: 5, sub: 5, dec: 90, striking: 41, tdAcc: 37, tdDef: 77 },
  { id: "f008", nom: "Joshua Van", categorie: "Poids mouche", taille: 165, allonge: 165, victoires: 17, defaites: 2, nuls: 0, ko: 53, sub: 12, dec: 35, striking: null, tdAcc: null, tdDef: null },
  { id: "f009", nom: "Alexandre Pantoja", categorie: "Poids mouche", taille: 165, allonge: 173, victoires: 30, defaites: 6, nuls: 0, ko: 27, sub: 40, dec: 33, striking: 50, tdAcc: 48, tdDef: 69 },
  { id: "f010", nom: "Khamzat Chimaev", categorie: "Poids moyen", taille: 188, allonge: 190, victoires: 15, defaites: 1, nuls: 0, ko: 40, sub: 40, dec: 20, striking: 54, tdAcc: 58, tdDef: 88 },
  { id: "f011", nom: "Sean Strickland", categorie: "Poids moyen", taille: 185, allonge: 193, victoires: 31, defaites: 7, nuls: 0, ko: 39, sub: 13, dec: 48, striking: 42, tdAcc: null, tdDef: 80 },
  { id: "f012", nom: "Tom Aspinall", categorie: "Poids lourd", taille: 196, allonge: 198, victoires: 15, defaites: 3, nuls: 0, ko: 80, sub: 20, dec: 0, striking: 67, tdAcc: 100, tdDef: 54 },
  { id: "f013", nom: "Ciryl Gane", categorie: "Poids lourd", taille: 193, allonge: 206, victoires: 14, defaites: 2, nuls: 0, ko: 50, sub: 21, dec: 29, striking: 61, tdAcc: 23, tdDef: 50 },
  { id: "f014", nom: "Jack Della Maddalena", categorie: "Poids welter", taille: 180, allonge: 185, victoires: 18, defaites: 3, nuls: 0, ko: null, sub: null, dec: null, striking: 53, tdAcc: 16, tdDef: 70 },
  { id: "f015", nom: "Magomed Ankalaev", categorie: "Poids mi-lourd", taille: 191, allonge: 191, victoires: 20, defaites: 2, nuls: 1, ko: null, sub: null, dec: null, striking: null, tdAcc: null, tdDef: null },
  { id: "f016", nom: "Kayla Harrison", categorie: "Poids coq feminin", taille: 173, allonge: 168, victoires: 19, defaites: 1, nuls: 0, ko: 31, sub: 42, dec: 27, striking: null, tdAcc: null, tdDef: null },
  { id: "f017", nom: "Valentina Shevchenko", categorie: "Poids mouche feminin", taille: 165, allonge: 166, victoires: 26, defaites: 4, nuls: 1, ko: 31, sub: 27, dec: 42, striking: null, tdAcc: null, tdDef: null },
  { id: "f018", nom: "Mackenzie Dern", categorie: "Poids paille feminin", taille: 163, allonge: 161, victoires: 16, defaites: 5, nuls: 0, ko: 6, sub: 41, dec: 53, striking: null, tdAcc: null, tdDef: null },
  { id: "f019", nom: "Julianna Pena", categorie: "Poids coq feminin", taille: 170, allonge: 175, victoires: 12, defaites: 5, nuls: 0, ko: 25, sub: 42, dec: 33, striking: null, tdAcc: null, tdDef: null },
  { id: "f020", nom: "Virna Jandiroba", categorie: "Poids paille feminin", taille: 160, allonge: 163, victoires: 23, defaites: 4, nuls: 0, ko: 4, sub: 61, dec: 35, striking: null, tdAcc: null, tdDef: null },
  { id: "f021", nom: "Khabib Nurmagomedov", categorie: "Legendes", taille: null, allonge: null, victoires: 29, defaites: 0, nuls: 0, ko: null, sub: null, dec: null, striking: null, tdAcc: null, tdDef: null },
  { id: "f022", nom: "Georges St-Pierre", categorie: "Legendes", taille: 178, allonge: 193, victoires: 26, defaites: 2, nuls: 0, ko: 31, sub: 23, dec: 46, striking: null, tdAcc: 74, tdDef: null },
  { id: "f023", nom: "Conor McGregor", categorie: "Legendes", taille: 175, allonge: 188, victoires: 22, defaites: 7, nuls: 0, ko: 86, sub: 5, dec: 9, striking: null, tdAcc: null, tdDef: null },
  { id: "f024", nom: "Salahdine Parnasse", categorie: "Poids leger", taille: 178, allonge: 186, victoires: 23, defaites: 2, nuls: 1, ko: 35, sub: 30, dec: 35, striking: null, tdAcc: null, tdDef: null },
  { id: "f025", nom: "Arman Tsarukyan", categorie: "Poids leger", taille: 170, allonge: 183, victoires: 10, defaites: 2, nuls: 0, ko: 40, sub: 10, dec: 50, striking: null, tdAcc: null, tdDef: null },
  { id: "f026", nom: "Charles Oliveira", categorie: "Poids leger", taille: 178, allonge: 188, victoires: 25, defaites: 11, nuls: 0, ko: 16, sub: 68, dec: 16, striking: null, tdAcc: null, tdDef: null },
  { id: "f027", nom: "Max Holloway", categorie: "Poids leger", taille: 180, allonge: 175, victoires: 24, defaites: 9, nuls: 0, ko: 50, sub: 8, dec: 42, striking: null, tdAcc: null, tdDef: null },
  { id: "f028", nom: "Paddy Pimblett", categorie: "Poids leger", taille: 178, allonge: 185, victoires: 8, defaites: 1, nuls: 0, ko: 25, sub: 50, dec: 25, striking: null, tdAcc: null, tdDef: null },
  { id: "f029", nom: "Benoit Saint-Denis", categorie: "Poids leger", taille: 180, allonge: 185, victoires: 9, defaites: 4, nuls: 0, ko: 56, sub: 44, dec: 0, striking: null, tdAcc: null, tdDef: null },
  { id: "f030", nom: "Mateusz Gamrot", categorie: "Poids leger", taille: 177, allonge: 178, victoires: 9, defaites: 4, nuls: 0, ko: 33, sub: 22, dec: 44, striking: null, tdAcc: null, tdDef: null },
  { id: "f031", nom: "Dan Hooker", categorie: "Poids leger", taille: 183, allonge: 191, victoires: 14, defaites: 10, nuls: 0, ko: 50, sub: 14, dec: 36, striking: null, tdAcc: null, tdDef: null },
  { id: "f032", nom: "Renato Moicano", categorie: "Poids leger", taille: 181, allonge: 183, victoires: 13, defaites: 7, nuls: 0, ko: 15, sub: 54, dec: 31, striking: null, tdAcc: null, tdDef: null },
  { id: "f033", nom: "Rafael Fiziev", categorie: "Poids leger", taille: 173, allonge: 182, victoires: 8, defaites: 5, nuls: 0, ko: 50, sub: 0, dec: 50, striking: null, tdAcc: null, tdDef: null },
  { id: "f034", nom: "Mauricio Ruffy", categorie: "Poids leger", taille: 180, allonge: 191, victoires: 5, defaites: 1, nuls: 0, ko: 80, sub: 0, dec: 20, striking: null, tdAcc: null, tdDef: null },
  { id: "f035", nom: "Beneil Dariush", categorie: "Poids leger", taille: 178, allonge: 183, victoires: 17, defaites: 8, nuls: 1, ko: 18, sub: 29, dec: 53, striking: null, tdAcc: null, tdDef: null },
  { id: "f036", nom: "Quillan Salkilld", categorie: "Poids leger", taille: 183, allonge: 191, victoires: 5, defaites: 0, nuls: 0, ko: 60, sub: 20, dec: 20, striking: null, tdAcc: null, tdDef: null },
  { id: "f037", nom: "Manuel Torres", categorie: "Poids leger", taille: 178, allonge: 185, victoires: 5, defaites: 1, nuls: 0, ko: 80, sub: 20, dec: 0, striking: null, tdAcc: null, tdDef: null },
];
